### ISSUE TITLE
Projektin posteri

### ISSUE THREAD

**Issue by atarv** [kjoonas1/Vaalikartta#106]
Moodlesta:

> **Project presentations pdf**
> Submit the poster of the open doors presentations day here (must be pdf). Only one of the group needs to submit. In the poster, include the names of the project participants, an abstract of your project, data resources and their IPR information, programming languages and techniques/platforms/frameworks  used, a  link to the running software (e,g. Heroku), a link to Git repository (if this applies to your agreed publication scheme), possibly pictures of your UI, and possibly pictures of the design of your software. 
> 
> The information in the poster maybe used for presentations about the Faculty's teaching.

**Comment by jurakrhu** [comment]
Tehdäänks tää siis Google Slidesilla tai jollai

**Comment by atarv** [comment]
Sanoisin että tyyli vapaa. Lopputuotteen pitäs olla pdf-tiedosto, jossa on yksi nätisti tulostuva sivu. Ehkä jossakin voi tulostaa A3 kokoisena (ja väreissä)?
