### ISSUE TITLE
README.md:n laatiminen repon päällimmäiseen kansioon

### ISSUE THREAD

**Issue by atarv** [kjoonas1/Vaalikartta#62]
Voisi kirjoittaa mm. kurssista, millainen projekti/sovellus, toteutustekniikat yms yms.

**Comment by jurakrhu** [comment]
Oletan että tämä tehdään tähän tyyliin: https://gist.github.com/PurpleBooth/109311bb0361f32d87a2

**Comment by atarv** [comment]
Tossa on tosiaan ihan hyvä runko. Deployment, Contributing ja Versioning -otsikot vois jättää pois. Pääpaino sovelluksen esittelyssä (mitä sillä voi tehdä, miksi tehtiin, TIEA207 kurssista mainintaa jne.), eikä niinkään teknisissä yksityiskohdissa.

**Comment by atarv** [comment]
Vois vielä lisätä miten sovellus käynnistetään. `npm start` jne. Tietysti, jotta backend toimii niin tarvitsee paljastaa kans MongoDB:n salasana (`PASSWD`), mutta tuskinpa tuo haittaa kun sillä tunnuksella on vain lukuoikeudet. Mä voin vielä laittaa tarkemmat linkit ja päivämäärät millon datat on haettu.
